### ISSUE TITLE
Design Vatican theme

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#10]
The Vatican exhibits will need their own branding.

**Comment by ggeisler** [comment]
@blalbrit Below is a first draft for purposes of starting a dialogue with BAV about the visual design of the Vatican exhibits. It is intentionally based heavily on the branding used on their site at https://digi.vatlib.it/mss because I'm not sure how important that visual design is to them, or whether we are free to completely deviate from it and use other colors, etc. So this is just the first of what I'd  expect to be multiple iterations of design + feedback to hone in on what they might want, visual design wise.

<img width="630" alt="theme-example-v1" src="https://user-images.githubusercontent.com/101482/40813721-317895b2-64f1-11e8-818a-d3f5ef776045.png">

Note that the content on the page between the masthead and the footer is simply placeholder content to give the design realistic context; I'm not suggesting this as actual home page content (we can work on that with them as the exhibit content becomes more finalized).

Here are some of the things we'll want to discuss with them:

- Color palette - is the blue as the primary color something they want to stick with? Do they have other ideas for colors?

- Institution icon(s) - I used the vatlib icon in the brandbar, though it is not ideal on a blue background (and it's too tall to really work in the brandbar unless we increase the brandbar height). Do they have other institution icons by chance?

- Institution name in brandbar - Do they want this? If so, what is the exact name they want to use? I just used "DigVatLib" because that is what is used in the logo (not visible here because of the logo size).

- Footer - What's in the mockup is pretty much what's on their current site. Do they still want the copyright and/or NTT content in the footer? Do they have other information they'd like to see in the footer?

- Question for Stanford - Do we want/need to show any SUL branding or logos anywhere in the header or footer of the site? Or should the branding strictly reflect the BAV only?

**Comment by blalbrit** [comment]
Thanks @ggeisler - good food for thought. I believe we will want a SUL logo in the footer, similar to what you have done for NTT in the mock above.

We can follow up with them on the other questions in the call tomorrow.

**Comment by ggeisler** [comment]
Paola to investigate whether there is an alternative BAV/DVL logo that will work better on the blue background.

**Comment by ggeisler** [comment]
Just to keep track of the Vatican-pending questions, I spoke with Paola today and she asked me to email her with the questions she needs to follow up on. Here are the two questions from my email that apply to this ticket (the visual design of the project generally):

> The DVL logo image that I took from the DVL site does not work well with the blue background, or the limited height of top blue bar. We might be able to increase the height of the blue bar, but to use the current DVL logo we would have to rethink the color scheme to avoid using the blue background (which I think we want to use for continuity with the current DVL site). Does the DVL have any other logo options that might work better on the blue background? Or, do you have any visual designers at the Vatican Library who might be able to rework the logo to accommodate a blue background?

> We discussed the need to recognize Mellon in the footer. We can work on the final design of the footer after we find out from Don whether we should use a specific Mellon logo, etc.
