### ISSUE TITLE
Add "Resource type" for Manuscripts and Page Details

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#108]
Let's just go with Page Details until we have something better to call it? Similar to Parker approach.

For the "Page Details", #82 needs to be merged first.

**Comment by mejackreed** [comment]
cc @ggeisler

**Comment by ggeisler** [comment]
Yes, there was a tentative but positive reaction to "Page details" as the label, so it makes sense to go with that, at least for now.

**Comment by cbeer** [comment]
I think this is now "Manuscript" and "Annotation"?

**Comment by mejackreed** [comment]
Agreed. "Manuscript" and "Annotation" unless we hear back differently later on

**Comment by cbeer** [comment]
Then, done.
