### ISSUE TITLE
Add short narrative to manuscript detail (show) page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#11]
- Add short narrative to each (or some) manuscript detail page; show manuscript narrative distinct from metadata in some way
- Manuscript feature page would have thumbnail for each manuscript (e.g., using search result widget), clicking on thumbnail links to item show page, which has the additional non-metadata manuscript narrative
- Additional narrative should allow hyperlinks so can link names, etc. to another detail page

Easiest solution would be for Vatican to simply use a custom field for this, but that doesn't satisfy the "make it distinct from other metadata fields" goal.

**Comment by ggeisler** [comment]
I believe we've discussed a potential way to use a custom field (but generated outside of the UI, I think) for the manuscript narrative. Assuming we can use a custom field, the curator can provide the narrative text by editing the manuscript detail page and entering the text into the custom field.

Here's the proposal for displaying the custom field if it has a value:

<img width="461" alt="manuscript-narrative" src="https://user-images.githubusercontent.com/101482/41804296-db023da0-7648-11e8-99b0-f4a213958dde.png">

The note E is where the custom field would go, under the heading "Curatorial narrative" (I think we might need to display a translation for that if the user is in the `it` locale, too). If a given manuscript does not have a value for this custom field, we shouldn't show the "Curatorial narrative" heading.

The idea in the mockup is that we use a Bootstrap row to contain a)  the part of the manuscript metadata that is initially displayed (see #126 for details) and b) the Curatorial narrative section. Each of those is 6 columns. After those two sections we start a new Bootstrap row so the remaining page content can go back to 12 columns. The initially visible manuscript information metadata doesn't usually have long values, so it should usually look fine in 6 columns.

For viewports narrower than `lg` (e.g., 991px and below) we could just make those two columns `12-col` so there is sufficient width for each. But ideally we should do this so that the Curatorial narrative section comes first, above the Manuscript information section, for the narrower viewports. 

_Paola liked this approach, so the design review we need is for technical feasibility and concerns/suggestions for anything I'm overlooking._

**Comment by cbeer** [comment]
> Additional narrative should allow hyperlinks so can link names, etc. to another detail page

Are we expecting curators to enter raw html, markdown, etc?

Can they enter the narrative as plain text, like our other custom fields, or do we need to provide a WYSIWYG editor (somehow..)?

Your mockup also suggests curators will enter multi-paragraph text. Is there any other styling we need to support?

**Comment by ggeisler** [comment]
Here's the questions I asked Paola on 6/25:

> I know we want to allow the curator to include links in the text. Does the curator also need to be able to style or format the text, such as using bold or italics for parts of the text?

> Or will the curator want any other more complex things, like including a list or headings?

> I assume we should allow for multiple paragraphs in the narrative (as shown in the mockup), but if it will always only be one paragraph, please let me know as that will be simpler to implement. 

@blalbrit If you discuss this with Paola it could be helpful to also ask ***how*** she expects the curators to enter the narrative text. Is it reasonable to expect them to enter HTML (e.g., a paragraph tag with a coded link tag within it) directly, for example? Or if not, would they be able to indicate links and/or any desired styling via a simplified Markdown format? (Either of which, I believe, would be less work to implement than a WYSIWYG formatting affordance.)
