### ISSUE TITLE
Provide names and slugs for each exhibit

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#110]
@blalbrit @ggeisler  is there a name or slug that should be used be sides "pathway_a" for each exhibit?

**Comment by blalbrit** [comment]
I'll ping Paola on this - I think ultimately it is her call about what the exhibit slug should express.

B.

**Comment by cbeer** [comment]
Did this get resolved by #151 ?

**Comment by mejackreed** [comment]
Yep.
