### ISSUE TITLE
Add 3-item configuration to Mirador configurator

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/vatican_exhibits#114]
Following on #92, based on the design in [exhibits/#1002](https://github.com/sul-dlss/exhibits/issues/1002), we want to have a 3-up view.

![](https://user-images.githubusercontent.com/101482/33741082-38a092f6-db60-11e7-85ba-49b205c092a5.png)

To create this in the Mirador UI, create a 1x2 layout, and then use the layout controls on one of the windows to "add slot below". This will result in a [[2x1][1x1]] layout, as pictured above:

![1x3](https://user-images.githubusercontent.com/145874/41565878-9891f660-730d-11e8-8afb-87b15d1af5d5.gif)

The layout description for more complex layouts is a tree structure we made up to describe these. The important part is the parent>child relationships and the "row" of "column" types. Using the "Add slot to the right", "add slot below" controls reorganise this tree. To inspect this state, and see examples of this tree structure, create a layout as described above, and then call `[myMiradorInstance].saveController.currentConfig.layout`.

### Example
``` json
{  
   "type":"row",
   "children":[  
      {  
         "type":"column",
         "depth":1,
         "value":0,
         "id":"4f7962fc-2472-4be1-884d-924f69e5c66e",
         "x":3,
         "y":3,
         "dx":426.5,
         "dy":508,
         "address":"row1.column1"
      },
      {  
         "type":"column",
         "id":"e6a5a8ca-0c3d-4ae5-b377-7b259e9d9b22",
         "children":[  
            {  
               "type":"row",
               "depth":2,
               "value":0,
               "id":"e8109553-d23c-4f0b-b34a-d3dc61a2cfd1",
               "x":435.5,
               "y":3,
               "dx":426.5,
               "dy":251,
               "address":"row1.column2.row1"
            },
            {  
               "type":"row",
               "id":"32dd9490-d70f-46a7-bb4e-d34a80805431",
               "depth":2,
               "value":0,
               "x":435.5,
               "y":260,
               "dx":426.5,
               "dy":251,
               "address":"row1.column2.row2"
            }
         ],
         "depth":1,
         "value":0,
         "x":435.5,
         "y":3,
         "dx":426.5,
         "dy":508,
         "address":"row1.column2"
      }
   ],
   "depth":0,
   "value":0,
   "x":3,
   "y":3,
   "dx":859,
   "dy":508,
   "address":"row1",
   "id":"ff5375e7-ccf7-43f6-bfc0-4bc8ed661bff"
}
```

Note that the addresses that will need to be given to the `windowObjects` are those in the leaf nodes of the tree above, for example:

``` javascript
windowObjects: [{
  loadedManifest: "http://iiif.harvardartmuseums.org/manifests/object/299843",
  viewType: "ImageView",
  slotAddress: "row1.column1"
  },
{
  loadedManifest: "http://media.nga.gov/public/manifests/nga_highlights.json",
  slotAddress: "row1.column2.row1",
  viewType: "ImageView"
},
{
  loadedManifest: "http://media.nga.gov/public/manifests/nga_highlights.json",
  slotAddress: "row1.column2.row2",
  viewType: "ImageView"
}],
```

**Comment by mejackreed** [comment]
Resolved in #129
