### ISSUE TITLE
Configure facet fields

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#119]
Part of #9. 

Figuring out all details requires discussion with at least one developer who is somewhat familiar with the project TEI structure.

Here's a tentative recommendation for the facets, discussed with Paola on 6/21:

<img width="356" alt="suggested-facets-v1" src="https://user-images.githubusercontent.com/101482/41744909-1a66ff5c-755a-11e8-8d30-27cc826c31d6.png">

**Comment by caaster** [comment]
@blalbrit ask Vatican to normalize dates? can we get rid of some set of date data because it is redundant?
