### ISSUE TITLE
Investigate the creation of region-based annotation thumbnails

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#122]
The mockup for #109 suggests using the generic annotation thumbnail image to represent annotation search result items. However, if we can figure out a way to use an annotation-specific thumbnail based on the canvas or annotation region on the canvas, that would be more visually attractive and potentially provide additional information for the user. Here's the same mockup used in #109, but with the idea of region-based thumbnails:

<img width="551" alt="annotation-region-thumbnails" src="https://user-images.githubusercontent.com/101482/41750402-886e1b0a-7570-11e8-9df2-d4283a554697.png">

One challenge that might come up has to do with thumbnail aspect ratio. If the annotation region is small, like a point or very narrow bounding box would produce, will it look awkward when it is sized to 100px wide to match other thumbnails?

If we can't find a way to use the annotation region for the thumbnail, even using the associated canvas image might be an improvement over the generic annotation thumbnail image. The drawback is potentially having the exact same canvas repeated on the same results page, when multiple annotation result items are associated with the same canvas.

**Comment by cbeer** [comment]
As long as we can make some assumptions about the Vatican annotations and IIIF environment, this should be fine. I think the assumptions we need to make are:

- Annotations always point at a single IIIF canvas (or, at least, the thumbnail shown is always the first canvas in the list of targets)
- IIIF canvases are resolvable (e.g. https://digi.vatlib.it/iiif/MSS_Barb.gr.252/canvas/p0001 returns a JSON response for the canvas), so we can get the IIIF Image API endpoint
- We can constrain the type of region-based annotation to just single, rectangular regions that have a `oa:FragmentSelector` with an `xywh` value

And then some assumptions that would be really nice to make:
- Can we assume that all annotations have the same general structure / are generated by the same tool?
-

**Comment by mejackreed** [comment]
I'm not sure we can make that assumption each time, but we have a general idea of what the annotations will be like. @aeschylus and I wrote a "remediation" task that kind of addresses some of this: https://github.com/mejackreed/annotot/blob/master/lib/tasks/annotot_tasks.rake

Mirador modified how it creates annotations midstream of their annotation work. I'm not sure if that significantly affected tags, but maybe a bit more analysis is needed.

**Comment by cbeer** [comment]
For older objects, the FragmentSelector has `xywh=0,0,0,0` and a rich SVG bounding box. If we want to use these, we might need to remediate old items.
