### ISSUE TITLE
Manuscript show page: Manuscript metadata section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#126]
Related to #9 and part of #125.

The basic idea of the manuscript metadata section on the manuscript show page is to show all "Manuscript information" metadata fields that have values. A manuscript is very likely to have additional fields; these we should initially hide and provide a "More details" button the user can use to expand the display to show all manuscript level metadata fields, as in this mockup

### Example of initial display
<img width="164" alt="vatican_graffle__public___show_page_for_mss_version_2" src="https://user-images.githubusercontent.com/101482/41802673-5663a860-7637-11e8-8848-1471d0de9208.png">

### Example of "More details" display
<img width="356" alt="vatican_graffle__public___show_page_for_mss_version_2_-_expanded" src="https://user-images.githubusercontent.com/101482/41804137-407b5a66-7646-11e8-8d6e-86cee9e31adc.png">

### Manuscript fields
The TEI elements that apply to the manuscript (as opposed to manuscript sections, or parts) are within an `<msDescription n="y">` element. The key distinguisher is the attribute `<n="y">` part. (As noted in #121, our fixtures TEI currently not include this attribute for the `<msDescription>` element.)

We need to discuss as a team what's the best way to convey which TEI elements go into which metadata sections. There are many fields, and in addition to the initially displayed Manuscript information section, there can be Description, Administrative information, and History sections.

As an example, here are the fields that, if they have a value, should go under the Manuscript information section:

Library
Collection
Shelfmark
Ocelli nominum
Date
Dated Mss
Beginning date
Ending date
Date of text
Country
Region
Place
Support
Physical shapes
Height
Width
Depth
Extent
Content
Overview

There are many more potential fields for the Description section, but only a few potential fields for the Administrative information and History sections.

**Comment by cbeer** [comment]
Assumption: The Vatican curators don't need the ability to reorder, relabel, or add custom fields. We'll probably need to override the whole metadata display provided by blacklight/spotlight to implement this design.
