### ISSUE TITLE
Manuscript show page: Bibliography section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#127]
Related to #9 and part of #125. 

_This ticket needs design review from the development team to determine if this is enough information to work with and, if not, what additional information is needed. @blalbrit One question for you is whether we need to make bibliography reference items first-class objects, as with Parker (but without the link to Zotero part). It hasn't come up in our discussions with the Vatican, but we might need to be sure they don't need to be before proceeding with indexing (?)_

If a manuscript has one or more bibliography reference items, display the Bibliography section heading and the reference items below it, with the following details:

- Only display the first two bibliography items when the page is loaded. If there are three or more items, hide them and display the "Expand bibliography" button. This is very similar to Parker, except with Parker we displayed up to three items before hiding (here we potentially have much more content to show vertically so limiting to two items makes sure the user knows about them but saves a bit of vertical space to show the manuscript parts section).

- When the user selects the "Expand" button, show all remaining bib items and change the button to be a one with the label "Collapse bibliography". 

- Selecting the "Collapse bibliography" show return the display to the initial state of up to two items displayed.

- [Parker is a good example](https://exhibits.stanford.edu/parker/catalog/gz764sr2328) of exactly what we need, but I suggest we try using `btn-sm` rather than `btn-default` for the expand/collapse buttons to make the buttons a bit smaller.

<img width="297" alt="vatican_graffle__public___show_page_for_mss_version_2" src="https://user-images.githubusercontent.com/101482/41802692-870c4f44-7637-11e8-8f34-03c44f2b8c0c.png">

### Relevant TEI elements 
Here are the paths in the TEI that I believe are associated with the bib item elements:

Author: `titleStmt/author/alias/authorityAuthor[@rif='aut']/text()`
Title: `titleStmt/title[@level!='u' or not(@level)]/@value`
In: `TEI.2/teiHeader/fileDesc/titleStmt/title[@level='u']/@value`
In: `TEI.2/teiHeader/fileDesc/seriesStmt/title[@level = 's']/alias/authorityTitleSeries[@rif='aut']/@value`
Type of continuing resources: `TEI.2/teiHeader/fileDesc/seriesStmt/title[not(@level)]/alias/authorityTitleSeries[@rif='aut']/@value`
Series: `TEI.2/teiHeader/fileDesc/seriesStmt/title[@level = 'm']/alias/authorityTitleSeries[@rif='aut']/@value`
Enumeration: `TEI.2/teiHeader/fileDesc/seriesStmt/title/@n`

### Example TEI source of bib item
As a specific example, here's the relevant TEI for one bib item in manuscript [Vat.gr.984](https://digi.vatlib.it/tei/Vat.gr.984.xml):

```xml
<TEI.2>
    <teiHeader status="new">
      <fileDesc>
        <titleStmt>
          <title type="title">Conservation treatments on the greek manuscripts of the "Fondo antico" in the Vatican library under Paul V (1605-1621),</title>
          <title type="title" level="u">Studi in onore del cardinale Raffaele Farina, a cura di A.M. Piazzoni, I (Studi e testi, 477),</title>
          <author reg="person">Choulis, Konstantinos,</author>
        </titleStmt>
        <publicationStmt>
          <pubPlace>Città del Vaticano</pubPlace>
          <date TEIform="date" value="">2013</date>
        </publicationStmt>
        <notesStmt>
          <note anchored="yes">151.</note>
        </notesStmt>
        <sourceDesc default="NO">
          <msDescription>
            <msIdentifier type="primary">
              <repository>Biblioteca Apostolica Vaticana</repository>
              <idno TEIform="0" n="Vat.gr." rend="Vat.gr.00984zzzzz" type="bib">Vat.gr.984</idno>
            </msIdentifier>
          </msDescription>
        </sourceDesc>
      </fileDesc>
```
 
### Example display of bib item
And here is how that item is [displayed at DigVatLib](https://digi.vatlib.it/mss/detail/Vat.gr.984): 

> Choulis, Konstantinos, Conservation treatments on the greek manuscripts of the "Fondo antico" in the Vatican library under Paul V (1605-1621), In Studi in onore del cardinale Raffaele Farina, a cura di A.M. Piazzoni, I (Studi e testi, 477), 2013

I think the display could use better formatting so if we want to attempt that we might want to use `<span>`s with distinct class names for the elements that compose the bib item, so we have targets for styling.

**Comment by cbeer** [comment]
How do we find bib items in the TEI? Is there something that identifies them?

**Comment by caaster** [comment]
@blalbrit please follow up with Paola

**Comment by ggeisler** [comment]
Here's an example manuscript with the `<bibl` element that contains the bibliography item that we now care about (as opposed to the elements in my original comment above): https://digi.vatlib.it/tei/Urb.lat.10.xml

**Comment by jkeck** [comment]
@ggeisler if memory serves, we did something along the lines of "if there are 5 or less bibliographies then show them all, if there are more than 5 show two, and hide the rest behind a toggle"

Do we want to do the same thing here, or keep it simple w/ just > 2 gets hidden behind a toggle?

**Comment by ggeisler** [comment]
Discussed with @jkeck and given there are so few bib entries for most manuscripts, and seeing how most (or all) section bib entries are the same entry just with a specific page reference in that entry, we think it makes more sense to dispense with the Bibliography heading and display bib entries as a regular metadata field, with a label "Bibliography" and the bib entry value as the field value. 

Same pattern for both manuscript level and section level (i.e., `<bibl>`s in sections are displayed as a metadata field in that section).
