### ISSUE TITLE
Manuscript show page: Part of the manuscript section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#128]
Related to #9 and part of #125.

TBD: details related to this section of the manuscript show page:

<img width="334" alt="vatican_graffle__public___show_page_for_mss_version_2" src="https://user-images.githubusercontent.com/101482/41802712-b276bd2c-7637-11e8-95bc-0956ad54f461.png">

### Heading for each manuscript section
To match what's in the mockup above, the heading for each section (the identifying section text that is visible even when a section is collapsed) needs to be constructed from several elements and element attributes:

![section-heading](https://user-images.githubusercontent.com/101482/42002722-21507b5a-7a1d-11e8-8f0b-f45b2c487f95.png)

Notes below correspond to the mockup above and use this manuscript as an example: 
`TEI` doc: https://digi.vatlib.it/tei/Barb.gr.221.xml
DigiVatLib catalog record: https://digi.vatlib.it/mss/detail/Barb.gr.221

Within the `<msDescription n="n">` element:

A: The text value of`<locus>47r-v. 49r-54v</locus>` - **row 46** in the spreadsheet

On a new line,

B: The text value of `<authorityAuthor date="129-199" rif="aut" type="person">Galenus, Claudius,</authorityAuthor>` - **row 47** of the spreadsheet (`rif="aut"` is the identifying attribute)

C: The value of the `date` attribute from the same element as in B above, followed by a period.

D: The value of the `<title scan="@1De diebus decretoriis (fragmenta)_supplied" type="supplied" value="De diebus decretoriis (fragmenta)">De diebus decretoriis (fragmenta)</title>` element where the type attribute is `supplied` - **row 53** of the spreadsheet. This value goes in italics (to help it stand out as a title).

**Comment by mejackreed** [comment]
Look at `<locus>`

**Comment by cbeer** [comment]
Question: Can we match TEI manuscript sections to IIIF images (see `<locus>`?)

**Comment by mejackreed** [comment]
Working examples here: 

https://digi.vatlib.it/tei/Barb.gr.252.xml
https://digi.vatlib.it/iiif/MSS_Barb.gr.252/manifest.json

Doesn't look like an exact string match is available.

**Comment by cbeer** [comment]
I've had a thought about how to deal with the part metadata.. if we can index the data as a JSON blob that suspiciously resembles the solr document response, we might be able to load it up as a `SolrDocument` (as far as Blacklight is concerned) and get to use all the rendering pipeline + field configuration stuff.

Of course, the trick is figuring out how to convince the indexing pipeline of that.. Right now, the `compose` step flattens each value down into a single hash, but maybe we can convince it to output an array of hashes?

**Comment by jkeck** [comment]
If we are indexing the data as a JSON blob, would Traject have an issue with that? (it's just an array of strings, no?)

Then we would just worry about the deserialization on the render side.

Perhaps I'm miss-understanding the intent.

**Comment by ggeisler** [comment]
Based on team discussion it won't be feasible to to show a thumbnail for each manuscript section. I'll figure out another way to clearly distinguish the sections visually, but development can proceed without worrying about that aspect of things. I'll do some visual design on it later.
