### ISSUE TITLE
Index Vatican TEI data

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/vatican_exhibits#137]
per https://docs.google.com/spreadsheets/d/1oKdzgW3_g38UdT47ETc6RON6U-MRZbRxFMxkXk0Uy1M/edit#gid=0.

**Comment by cbeer** [comment]
Related to #121?

**Comment by cbeer** [comment]
@ggeisler: We've indexed (and displayed) the rows on the spreadsheet for headings "General" and "Description". What, if anything, do we need to do with "Administrative Information" and "History", besides make text discoverable in a full-text search?

**Comment by ggeisler** [comment]
@cbeer I don't think anything. These don't need to be faceted or fielded searchable, so I think if they are in the general index and displayed, that's it. Do you have any specific suspicion there might be something else we need to consider for these fields that I'm not thinking of?

**Comment by cbeer** [comment]
Nope; I'm going to close this ticket.
