### ISSUE TITLE
Add Italian translations for custom UI elements

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/vatican_exhibits#149]
We'll need Italian translations for the following Vatican-custom UI elements: 

e.g. 
![screen shot 2018-06-27 at 5 22 58 pm](https://user-images.githubusercontent.com/5402927/42006465-d37ee378-7a2e-11e8-99aa-01973ed62082.png)

- [ ] [Parts of this manuscript](https://github.com/sul-dlss/vatican_exhibits/blob/bc50aad672db4117bd9e1b0065b9db5572c1cb28/config/locales/en.yml#L12) (`catalog.parts_default.title`)

**Comment by ggeisler** [comment]
More Vatican-specific translations to keep track of (I've got a separate spreadsheet where I'm organizing all the Vatican, Spotlight, Blacklight-gallery, and Blacklight-maps translations needed to fully i18n Spotlight exhibits):

```
footer.copyright_heading
footer.copyright_text
footer.partnership_heading
footer.project_support_heading
footer.project_support_text
```
