### ISSUE TITLE
Support hierarchical tags in the Annotation Tag facet

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#15]
More appropriate end-user label for annotation tags TBD, although "Manuscript Tags" was discussed in https://github.com/sul-dlss/exhibits/issues/951.

Annotation tags (small percentage of, anyway) can be hierarchical:

- Animals - Lions
- Animals - Tigers

The Vatican wants to display the hierarchy with second-level indented (they don't like just showing the hierarchy flattened as in the Animals example above). There is never more than a second level of hierarchy. Roughly something like this (where "Curatorial Tags" is the annotation tags facet of relevance):

<img width="154" alt="33388303-d2a683ee-d4ec-11e7-95da-1a6d086282f2" src="https://user-images.githubusercontent.com/101482/39769949-81e916c2-52a2-11e8-9738-b54fee34d255.png">

Story here is to explore possibilities for expand/contract in a facet breaking on special character, or other implementation possibilities if they are feasible. See https://github.com/sul-dlss/exhibits/issues/951 for more discussion and examples.

**Comment by ggeisler** [comment]
I think this ticket needs a technical decision more than design at this point. From previous discussions it's not clear to me whether the team thinks indexing tags in a hierarchical way is feasible or not. Below is a summary of proposed designs for both the "is feasible" and "is not feasible" options.

### Option A: Design if indexing hierarchical tags is feasible
In another [ticket](https://github.com/sul-dlss/exhibits/issues/951) @blalbrit noted that Argo does include hierarchical tags ('open the "Tags" facet, and look at the "Projects" tag'). I don't know if that implies we should be able to do it for the Vatican or not, but if it does, here's the suggested design:

* We'll label the facet for these tags "Manuscript Tags" (pending Paola's approval or someone coming up with a better term).
* We only need to worry about one level of hierarchy and not all tags will have child tags.
* My understanding is they mark up child tags consistently, using a dash or similar character to indicate the text following that character is a child tag:

> - Animals - Lions
> - Animals - Tigers

So, when showing this Manuscript Tags facet we'd initially show all parent-level tags, where the label for a parent tag with one or more child tags is prepended with a disclosure triangle (Animals and Bicycles in the screenshot below):

<img width="147" alt="closed" src="https://user-images.githubusercontent.com/101482/40740934-ee0ca6c6-63fe-11e8-969c-d830f1a5c224.png">

Ideally, the parent tag is selectable. It shows the total of itself (I don't know whether they ever tag with the parent label alone when it has children) and all child tags. Selecting a parent tag produces a result set that include everything tagged with the parent or its children tags.

When the user opens the disclosure triangle for a parent tag, it reveals the children tags:

<img width="151" alt="open" src="https://user-images.githubusercontent.com/101482/40741058-454f5d7a-63ff-11e8-8b44-894e5d63f2de.png">

Each child shows its total and is selectable; the search result set includes only items with that child tag. 

The user can open parent tags independently (i.e., more than one parent tag can be open to reveal its children tags at the same time).

### Option B: Design if indexing hierarchical tags is *not* feasible
We simply treat each tag as an independent tag, as we normally do. 

(Depending on the actual separator character(s) they are using to indicate child tags, we might want to do a character substitution to display a more simple separator character.)

The resulting facet display is just a normal flat list of the tags:

<img width="149" alt="flat" src="https://user-images.githubusercontent.com/101482/40741459-71877912-6400-11e8-9676-26b3ae2b2a7e.png">

Option B is obviously far simpler than Option A, but note that the Vatican was quite adamant that they preferred something similar to Option A.

**Comment by mejackreed** [comment]
Some tags are here: https://github.com/sul-dlss/bav_stanford/blob/master/pathway_a.html#L158

**Comment by mejackreed** [comment]
Pending discussion with bav team.

**Comment by camillevilla** [comment]
Questions from 6/11 story time: -
- [ ] Order of magnitude for unique annotations tag values: high dozens to hundreds?
- [ ] Consistency of hierarchical tag markup (parentheses? Colons?)
- [ ] Is the controlled vocabulary locked? If no, when will tags be finalized?

**Comment by ggeisler** [comment]
On our call last week, Paola indicated the tag vocabulary is "basically final" (that was my interpretation of her response). I don't think we can assume there won't be any change to the vocabulary, but we can assume it won't change much. 

I didn't have a chance to ask her about the hierarchical tag markup (I was only able to ask about tags in the last minute of the call as we were wrapping up) but if I'm able to talk to her this week I'll try to get an answer on that.

Can answer the order of magnitude questions ourselves? We have access to the actual annotations, I think?

**Comment by ggeisler** [comment]
To track the Vatican-pending questions, note that I emailed Paola on 6/21 to ask:

> At some point we will need the translations for the tag values. I believe Jack sent you a CSV template on June 14th that you can use to provide the translations.

> You mentioned that you think the character used to indicate a hierarchical tag is a colon. When you have a chance, please confirm that a) the character used is a colon and b) that this is the only character used to indicate a hierarchical tag.

**Comment by ggeisler** [comment]
Vatican response to question about the delimiter to indicate a hierarchical tag:

> Hiearchy are expressed by () e.g. Animali (Serpenti) = Serpenti is a subunit of Animali

**Comment by cbeer** [comment]
Ok, and not a colon at all?

**Comment by ggeisler** [comment]
It doesn't seem like it from their response...

**Comment by cbeer** [comment]
Fixed by #158
