### ISSUE TITLE
Rename exhibits, to intended longterm names

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#151]
Names:

{vatican_server}/latin-paleography (pathway-a 1)
{vatican_server}/greek-paleography (pathway-a 2)
{vatican_server}/latin-classics (pathway-b)
{vatican_server}/palimpsests (pathway-c)
{vatican_server}/humanist-library (pathway-d)
{vatican_server}/overview (all manuscripts)

Also need to remediate the data stage env

**Comment by cbeer** [comment]
For remediating the existing data, can we just `db:drop` + `db:create`, since we haven't populated it with anything we care about yet?

**Comment by mejackreed** [comment]
Yup definately
