### ISSUE TITLE
Render annotation text as html

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#172]
133r: Pal.gr.220 — Titoli in mauscola a

![screen shot 2018-06-29 at 10 47 42 am](https://user-images.githubusercontent.com/1656824/42104468-de5e5c40-7b89-11e8-877f-3727e81c5f8e.png)

**Comment by cbeer** [comment]
Can we come up with a whitelist of what attributes we want to pass through? I'd also guess we don't necessarily want to pass through all their styling?

**Comment by mejackreed** [comment]
Yeah I think it will likely be on us to do this. All of this is unfortunately an artifact of the Microsoft Word copy/paste process.

**Comment by cbeer** [comment]
Ah; if none of it is intentional, can we just use `sanitize` and call it a day?

**Comment by mejackreed** [comment]
I'm guessing the `<p>`, `<em>` may be intentional.. but besides that yeah lets do it as easy as possible
