### ISSUE TITLE
Document and install a plain centos 7 machine with Spotlight + system dependencies

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#18]
What are options as an artifact?

Ansible, bash script that we scp on to a box

The documentation in the end is an annotated version of this installation script

**Comment by mejackreed** [comment]
Systems assumptions:
 - preferred database? maria
 - no auth systems
 - we aren't considering performance (not terrible)
 - monitoring concerns or storage limitations - communicate monitoring concerns to vat team.
 - log rotation - you should do something
 - no integrations w/ new relic or honeybadger
 - risks - all on one machine
 - memory concerns w/ sidekiq configs

**Comment by mejackreed** [comment]
Idea 💡 

 - Use docker 🐳  to prototype installation script
 - `install.sh` is our "documentation" 
 - ??

**Comment by mejackreed** [comment]
Ok.. So I think the final thing here is to maybe convert this into documentation rather than a shell script.

**Comment by mejackreed** [comment]
Perhaps also we need to have instructions about how / ordering of scripts to run.

**Comment by camillevilla** [comment]
Wiki page with instructions: https://github.com/sul-dlss/vatican_exhibits/wiki/Installing-Spotlight-for-Centos-7

**Comment by camillevilla** [comment]
@mejackreed contacted the Vatican team on 5/17 with these instructions.
