### ISSUE TITLE
Improve MSS show page "View details" interaction

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#196]
It's not too big a deal, but I wonder if we could tweak the View details button:

<img width="499" alt="view-details-link" src="https://user-images.githubusercontent.com/101482/42118958-25c0ea44-7bbc-11e8-98e0-8054f9b4c6e1.png">

To:
- Change the label to "Hide details" when the part is open
- Make the close interaction slower. That is, when you click the link to open a part, it slides open with what feels (I haven't looked at the JS so maybe I'm way off on this) like a few hundred ms delay. But when you close, it immediately closes. It would be nice if the close delay matched the open delay.

**Comment by mejackreed** [comment]
Fast collapse narrowed down to using this class in Spotlight: https://github.com/projectblacklight/spotlight/blob/master/app/assets/stylesheets/spotlight/_catalog.scss#L92

Same issue as reported https://github.com/twbs/bootstrap/issues/12093
