### ISSUE TITLE
Change the "icon" in the More/fewer details button

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#198]
There doesn't seem to be an ideal glyphicons icon for this, which would be ideal, but I wonder if we could try using `&raquo;` as the entity for the 'icon` here:

<img width="511" alt="barb_gr_221_-_pathway-a_-_blacklight-2" src="https://user-images.githubusercontent.com/101482/42119124-bd576922-7bbd-11e8-8100-ea593b1e5b19.png">

Here's how it might look using `&raquo;`:
<img width="170" alt="barb_gr_221_-_pathway-a_-_blacklight" src="https://user-images.githubusercontent.com/101482/42119179-3f9e2736-7bbe-11e8-884c-e4a842829706.png">

It's super small and I haven't found a good way to make it larger without making the button taller (which we don't want), but I think that even tiny this works better than the large version we have now. Note that I also reduced the `margin-left` to `3px` for the `.btn-caret` class.

Also, I'd kind of like to go with `btn-sm` for this button, just to keep the vertical height of things a bit smaller and make the button feel less important.

**Comment by camillevilla** [comment]
@ggeisler `&raquo;` sounds totally reasonable to me. I did some digging into what we've done in the past and found the "Expand bibliography" option below. I compiled the list of icons below in the process and thought it might be fun to compare our options 😅

## Blacklight facet carets
applied by CSS pseudoclass `::after`
```css
font-family: 'Glyphicons Halflings';
content: "\e114";
float: right;
color: grey;
font-size: 0.8em;
line-height: normal;
```
![blacklight facet pointing down](https://user-images.githubusercontent.com/5402927/42180606-b713771e-7dec-11e8-9142-2c5c84f8f176.png)
![blacklight facet pointing right](https://user-images.githubusercontent.com/5402927/42180608-b732c812-7dec-11e8-92c4-e7a5fe1bed81.png)

## Bootstrap caret
implemented through `border` witchcraft belonging to the `.caret` class

```css
display: inline-block;
width: 0;
height: 0;
margin-left: 2px;
vertical-align: middle;
border-top: 4px dashed;
border-top: 4px solid \9;
border-right: 4px solid transparent;
border-left: 4px solid transparent;
```


### Basic
Example: [fr670md2824](https://parker.stanford.edu/parker/catalog/fr670md2824)

Exhibits, Parker table of contents field
![basic bootstrap caret pointing down](https://user-images.githubusercontent.com/5402927/42180538-82d8de9e-7dec-11e8-8aec-42bd7d6d5ec2.png)
![basic_bootstrap_caret pointing right](https://user-images.githubusercontent.com/5402927/42180539-82f5c00e-7dec-11e8-9dbb-cbfca835be25.png)

### Modified
Slightly larger `border` width
Example: [VT full text search sample matches](https://exhibits-stage.stanford.edu/vt-test/catalog?utf8=%E2%9C%93&exhibit_id=vt-test&search_field=search&q=crimes)
```css
border-width: 6px;
color: #8c1515;
margin-left: 6px;
```
![modified bootstrap caret down](https://user-images.githubusercontent.com/5402927/42180635-cf34d202-7dec-11e8-9695-2d1f94b42d10.png)
![modified bootstrap caret right](https://user-images.githubusercontent.com/5402927/42180636-cf4ecc16-7dec-11e8-8c4a-e7ee60aa7602.png)

## &raquo; (`&raquo;`)
Example: [fr670md2824](https://parker.stanford.edu/parker/catalog/fr670md2824)
### Exhibits, metadata details
![double arrows right](https://user-images.githubusercontent.com/5402927/42180666-ee5a7f7e-7dec-11e8-9b09-ed420cfb88db.png)

### Exhibits, Parker bibliography
`&raquo;` is in a span with `font-size` slightly larger than the button text
```css
display: inline-block;
font-size: 1.2em;
font-weight: bold;
margin-left: 5px;
-webkit-transform: rotate(90deg);
transform: rotate(90deg);
```
![double arrows up](https://user-images.githubusercontent.com/5402927/42180579-9fa3e262-7dec-11e8-90f4-73eae8df57b9.png)
![double arrows down](https://user-images.githubusercontent.com/5402927/42180580-9fc2b246-7dec-11e8-890e-1ac0b691dd10.png)

**Comment by camillevilla** [comment]
@ggeisler I've put up a PR for the basic adjustment #212. 

Here's some styling for a larger caret that retains button height if you decide to adjust it when you come back:
![fewer details large](https://user-images.githubusercontent.com/5402927/42191202-81269eea-7e16-11e8-852b-9f710213ed52.png)
![more details large](https://user-images.githubusercontent.com/5402927/42191203-813cae24-7e16-11e8-9c62-c68c1fa8fdfb.png)

```css
.btn-caret {
  font-size: 20px;
  line-height: 18px;
  vertical-align: top;
}
```
