### ISSUE TITLE
Set initial config for Mirador widget to remove top-level main menu layout settings

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/vatican_exhibits#213]
![screen shot 2018-07-02 at 4 42 32 pm](https://user-images.githubusercontent.com/145874/42191339-32a45d7e-7e17-11e8-9c50-3c57774efa4b.png)

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/vatican_exhibits/pull/205 no?

**Comment by aeschylus** [comment]
Should be, but still seeing this on master.

**Comment by aeschylus** [comment]
Could be previous configs being resurrected though. Let me double-check.

**Comment by aeschylus** [comment]
Yeah, this is fixed.

**Comment by mejackreed** [comment]
Sweet!
