### ISSUE TITLE
Loading blank annotations for editing

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/vatican_exhibits#221]
Overview:
Vatican has requested a significant number of annotations loaded that outline areas to be transcribed (bounding boxes with no text content). The problem I need to solve is a) what format of annotations/annotation list to load into annotot and b) insure that those annotations are editable.

Current:
* Able to load an annotation list into annotot that then shows in Mirador (Urb.lat.1324 - pathway D - image 008 (f. 1v - the second 1v because, of course, there are two).
* Able to open one of those annotations for editing and save
![screenshot 2018-07-03 17 03 17](https://user-images.githubusercontent.com/796990/42250011-4b543d7c-7ee3-11e8-879e-38c68c4b6f8d.png)
![screenshot 2018-07-03 17 03 10](https://user-images.githubusercontent.com/796990/42250013-50ba4efa-7ee3-11e8-9a26-9fec1fccea74.png)

* Upon save, the annotation appears to save but returns "undefined" as its text.
![screenshot 2018-07-03 17 03 36](https://user-images.githubusercontent.com/796990/42250020-5835cc18-7ee3-11e8-9188-e041ed3cbcad.png)

Above produced from:
* file used in the rake task to index annos: https://gist.github.com/blalbrit/0ebcd9871ca73bc72119a0c0fa2a0ef1
* annos after initial load: https://gist.github.com/blalbrit/1fb3ee74ef3c653b9bf2a67e42f9afad
* annos after editing one (note how motivation is treated after save): https://gist.github.com/blalbrit/8f60dc675d54157ee791625260f58b06

Need guidance in two or three areas:
* Is the upload format okay/expected? If not, what format should I be targeting?
* what is happening after save of edited annotation? It seems to transform the annotation, but into something invalid.

@mejackreed - to discuss Thursday or Friday?

**Comment by mejackreed** [comment]
@blalbrit I have a working example now with the following revisions:

 - modify `resource` to be an array
 - modify `on` to be a `specificResource` `FragmentSelector`

See diff here: https://gist.github.com/mejackreed/5cb1cac5e226f51294c16b73bc1be599/revisions

**Comment by cbeer** [comment]
I think we also want an `on/within` reference to the manifest?

**Comment by mejackreed** [comment]
@blalbrit I've added an update if you look at https://gist.github.com/mejackreed/5cb1cac5e226f51294c16b73bc1be599/revisions that adds the `on/within` in the appropriate place.

**Comment by mejackreed** [comment]
Closing as this is not actionable by the team anymore
