### ISSUE TITLE
Enhance display of name fields

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#241]
I know this is fundamentally a data problem since the pseudo-TEI includes a comma after every value in these fields, but I wonder if we could strip the comma after the _last value_ for name-related fields when displayed in the manuscript and manuscript section metadata fields?

<img width="401" alt="vat_gr_586_-_greek_paleography_-_blacklight" src="https://user-images.githubusercontent.com/101482/42589492-fd714c6c-84f5-11e8-81eb-3f1e20fd5ba6.png">

I think this is relevant to these fields:

- Author
- OtherAuthor
- OtherName

Of course, we'd only want to do this for the last value in a given field because we often will show multiple values in the same field, such as in the first example of the screenshot above.

Alternatively, we could talk to the Vatican about doing some bulk cleanup of the pseudo-TEI to remove the trailing comma from their name values, since the only purpose (that I can think of) for doing that is anticipating that the comma is needed to display the values correctly (which I don't think is true). But I'm not sure if this is realistic? What do you think @blalbrit? (If cleaning up the TEI is potentially possible, there are some other things they could fix that would improve the UI as well, such as removing the period from their Language and Alphabet values, which they apply inconsistently.)

**Comment by cbeer** [comment]
We can; my understanding was the Vatican wasn't interested in having us normalize data?

**Comment by ggeisler** [comment]
Okay. Let's leave this one open until we have a chance to talk to Paola again. I wasn't involved in the discussion about not normalizing this sort of thing and want to be sure she understands the benefits.

**Comment by cbeer** [comment]
Ok. Until the values are normalized (or fixed in the metadata, or un-normalized for the facet field), we can't (easily) link names to a faceted search (see #244).

**Comment by ggeisler** [comment]
If we decide to do more work on the name fields, I just want to note that a secondary "should-have" would be to break each name out into a separate line, as in the outlined section of the mockup below. This will make it easier for the user to scan the names versus the current display with all names on the same line separated by commas.

A "nice-to-have" (unless we hear otherwise from BAV) would be to also show the title and date attributes values, when they are present for a name field, to match the display shown in the mockup.

<img width="356" alt="more-details" src="https://user-images.githubusercontent.com/101482/43020026-9d42cf8a-8c13-11e8-88dc-80fd51cebfee.png">

**Comment by ggeisler** [comment]
BAV indicated today that the name formatting highlighted in blue in the mockup of my previous comment is actually must-have. I think the formatting takes priority over linking the name values in the metadata, though linking would be ideal if we can do that as well. As shown in the mockup, each name should be on a separate line.

I'm not 100% sure we're currently matching the relevant elements correctly (though we might be) aside from the missing date, etc. stuff, so below I'll just start from scratch in guessing at how to deal with the name fields. We can iterate on the presentation if necessary after we see how things display. 

I believe there are three distinct name-related fields to deal with: Author, Other author, and Other name. Other author and Other name appear to be very similar; both match the `<name />` element and when the element includes a role or "external" or "internal" it goes under Other author, otherwise under Other name.

References to spreadsheet rows are to [this spreadsheet](https://docs.google.com/spreadsheets/d/1oKdzgW3_g38UdT47ETc6RON6U-MRZbRxFMxkXk0Uy1M/edit#gid=0).

## Author 
(rows 47 - and 48 but not sure the 48 pattern ever occurs):
`TEI.2/teiHeader/fileDesc/sourceDesc/msDescription/msPart/msContents/msItem/author/alias/authorityAuthor[@rif='aut']/text()`

Example match:
```xml
<author authorityID="4473" scan="@4473" type="internal">
  <alias>
    <authorityAuthor date="347-407." formal="Opere spurie e dubbie" rif="aut" title="s., patriarca di Costantinopoli," type="person">Iohannes Chrysostomus,</authorityAuthor>
  </alias>
</author>
```
Example desired display:
```
Iohannes Chrysostomus, s., patriarca di Costantinopoli, 347-407. Opere spurie e dubbie [internal]
```

So this is something like:
<author /> text() + title attribute value + , + date attribute value + formal attribute value + [type attribute value]

I'm not sure `formal` and `title` are common, so a more typical pattern might be:
<author /> text() + date attribute value  + [type attribute value]

or: `Apicius, Caelius, sec. I [internal]`

If there is a formal attribute value, there should be a period after the date value. Example: https://digi.vatlib.it/mss/detail/205918

Sometimes the date is part of the name value. 

## Other author 
(rows 49  and 50 but not sure the 50 pattern ever occurs):

`TEI.2/teiHeader/fileDesc/sourceDesc/msDescription/msPart/msContents/msItem/name[@role='internal' or @role='external']/alias/authorityAuthor[@rif='aut']/text()`

Example match:
```xml
<name authorityID="17682" role="external" scan="@17682">
  <alias>
    <authorityAuthor date="1922-" rif="aut" type="person">Milham, Mary Ella,</authorityAuthor>
  </alias>
</name>
```

Example desired display:
```
Milham, Mary Ella, 1922- [external]
```

I think this is just: 
<name /> text() + date attribute value + [role attribute value]

## Other name 
(rows 73 and 74 but not sure the 74 pattern ever occurs):

`TEI.2/teiHeader/fileDesc/sourceDesc/msDescription/msPart/msContents/msItem/name[@role!='internal' and @role!='external' or not(@role)]/alias/authorityAuthor[@rif='aut']/text()`

Example match:
```xml
<name authorityID="33531" role="scribe" scan="@33531">
  <alias>
    <authorityAuthor date="sec. XV" rif="aut" type="person">Moschus, Demetrius,</authorityAuthor>
  </alias>
</name>
```

Example desired display:
```
Moschus, Demetrius, sec. XV [scribe]
```

I think this is:
<authorityAuthor /> text() + date attribute value + [role attribute value]

An instance might not have one or both of the date or role attributes.

**Comment by mejackreed** [comment]
Thanks for the great details on this @ggeisler ! I was able to get name going. Do you have any handy examples of other author or other name? Looking back at the spreadsheet, it doesn't seem like we ever really found any examples of these.

**Comment by ggeisler** [comment]
@mejackreed At this point the easiest way to find examples might be to just look at random manuscript show pages, and look in the Parts sections. For example:

http://vatican-dev.sul.stanford.edu/overview/catalog/Vat_lat_3195 (has both an Author and an Other name)

http://vatican-dev.sul.stanford.edu/overview/catalog/Urb_lat_1 (has an Other author in some of the parts - not the first one, but others)

Let me know if that doesn't help. I don't have a list of ready examples handy, though, unfortunately.

**Comment by mejackreed** [comment]
Gotcha thanks. I'll dig in more tomorrow morning and look into these.
