### ISSUE TITLE
Update field label for "section" on Annotation show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#242]
Related to #207 (in that that ticket has to do the linking the value of this field, I believe).

It doesn't look like we've given the section field a human-friendly label on the annotation show page:

<img width="405" alt="lxxiiv__vat_lat_3225_ _nella_a_e_nella_-_latin_classics_-_blacklight" src="https://user-images.githubusercontent.com/101482/42590231-1483d03a-84f8-11e8-90a9-5b41e4b681ed.png">

The field label should be "Section" and I'd suggest moving it to be below the manuscript field, above the annotation text field.

**Comment by cbeer** [comment]
>  I'd suggest moving it to be below the manuscript field, above the annotation text field.

That needs to be done within the application, I think.

**Comment by ggeisler** [comment]
Ah, okay. This is a separate issue then but I can't get the field order change to stick when I move that field up on the Metadata page. I've tried several times but after saving, the order is back to the original order on the Metadata page. Maybe you can try to confirm, in case I'm doing something stupid?

http://vatican-dev.sul.stanford.edu/latin-classics/metadata_configuration/edit
