### ISSUE TITLE
Remove period from end of Collection values

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#243]
Unless there is a technical reason, or if we're following specific advice from BAV or @blalbrit on this, I'd suggest we remove the final period from the values of the Collection field, everywhere it occurs (facets and metadata displays).

<img width="448" alt="project_overview_-_blacklight" src="https://user-images.githubusercontent.com/101482/42591867-c517bfe8-84fc-11e8-8f13-f74464b7b7f7.png">

I know these are weird names for collections to begin with, but it seems like they'd be a little less weird and more readable without the final period, as in "Vat.lat" or "Borgh".

**Comment by cbeer** [comment]
I think we got this formatting directly from the Vatican, see e.g. https://digi.vatlib.it/search?k_f=0&k_v=

**Comment by ggeisler** [comment]
Okay, I see, I should've double-checked how they were currently doing it. Seems like an odd decision but it's their decision...
