### ISSUE TITLE
Link some metadata field values on Manuscript show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#244]
I'm guessing some of these will be easy, since they are already configured as facet fields. Not sure how hard it is to do for the ones that are not already configured as facets or fielded search fields, but I'd suggest we make as many of the following field values links (to a new search on that value, as in a faceted or fielded search) on the Manuscript show page only (not in search results, and the Annotation show page is already fine with the manuscript value linked):

- Collection
- Country
- Region
- Place
- Language
- Alphabet

These two date fields (not Beginning date or Ending date)
- Date
- Mss date 

And these name fields, where they would use the Name facet, rather than limiting to the field the value is specifically in on a given manuscript show page:
- Author
- Other author
- Other name

**Comment by ggeisler** [comment]
@cbeer @mejackreed I wonder if we should reopen this ticket, since it doesn't look like we're currently linking any of the fields in the original ticket description? This might be related to #241 and #244, although those seem to be specifically about name fields so I'm not clear why none of the other fields are linked.

Also, some of these fields, which I think used to appear in the metadata, now don't seem to appear. I'll write that up in a separate ticket in a minute, but perhaps it is all related.

**Comment by mejackreed** [comment]
Reopening this ticket to deal with finalizing linking fields @ggeisler mentions in this above comment.

**Comment by mejackreed** [comment]
Closing per f2f discussion on 8/15
