### ISSUE TITLE
About page (and feature pages) disappear when switching languages/locales

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/vatican_exhibits#264]
English: Includes "About" page

<img width="1530" alt="screenshot 2018-07-17 10 49 56" src="https://user-images.githubusercontent.com/796990/42836233-49fb29fa-89af-11e8-9328-c1ad67f68595.png">

Switch to Italiano, "About" page disappears

<img width="1525" alt="screenshot 2018-07-17 10 50 08" src="https://user-images.githubusercontent.com/796990/42836253-5edb7be0-89af-11e8-9734-b019c85608e5.png">

If this is expected behavior, we'll need to call this out to the Vatican team in training.

**Comment by jkeck** [comment]
@blalbrit is the Italian translated version of the About page published?

**Comment by blalbrit** [comment]
That's probably it @jkeck - I didn't understand how the feature worked :-)
