### ISSUE TITLE
Metadata fields missing from Manuscript metadata section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#268]
These fields don't seem to be showing up in the metadata section of the Manuscript show page:

- Language
- Alphabet

Example: http://vatican-dev.sul.stanford.edu/overview/catalog/Barb_gr_221 
Source: https://digi.vatlib.it/tei/Barb.gr.221.xml 
(I see `<textLang n="Greco." rend="grc">Greco.</textLang>` within the `<msDescription n="y">` section)

---
- Country
- Region
- Place

Example: http://vatican-dev.sul.stanford.edu/overview/catalog/Chig_L_VIII_296
Source: https://digi.vatlib.it/tei/Chig.L.VIII.296.xml
I see these elements within the `<msDescription n="y">` section:

```
<origPlace>
<country>Italia</country>
<region>Italia centrale</region>
<settlement>Firenze</settlement>
</origPlace>
```

The records are matching those facets correctly, so I think it is just the show page display that changed, maybe related to the work done for #244?

**Comment by camillevilla** [comment]
hi @ggeisler! I was able to resolve this by reindexing one of the `vatican-dev` exhibits.
http://vatican-dev.sul.stanford.edu/latin-paleography/catalog/Chig_L_VIII_296

Please let me know if these are showing up in the appropriate sections:
![restored_metadata](https://user-images.githubusercontent.com/5402927/44122880-956ea524-9fda-11e8-8d21-31807a62a46e.png)

**Comment by ggeisler** [comment]
@camillevilla Okay, great. This all looks pretty good, though there are a couple more things maybe you can look into:

- `Dated Mss` appears in both the Information section and the Description section. It should only be in the Information section.
-  If you click the "Italiano" link from the manuscript metadata you get two result items. But if you use the Language facet and click the "Italiano" value, you get three result items. This probably has to do with the messiness of the source data, but it feels unsatisfying from a UX perspective, like the application is unreliable. So maybe you can take a look and see if this is something that could be fixed?

**Comment by camillevilla** [comment]
@ggeisler 

- `Dated MSS` is another one of the duplicated fields that shows up twice in the Curation > Metadata. I've toggled it off in Description
- The two Language facets rely on different fields:
  - [Manuscript metadata](http://vatican-dev.sul.stanford.edu/overview/catalog?f%5Bms_language_ssim%5D%5B%5D=Italiano.): `http://vatican-dev.sul.stanford.edu/overview/catalog?f%5Bms_language_ssim%5D%5B%5D=Italiano.`  
![ms_language_ssim](https://user-images.githubusercontent.com/5402927/44124244-108d6492-9fe1-11e8-9f85-552c45b198ed.png)

  - [ Search results > Facet](http://vatican-dev.sul.stanford.edu/overview/catalog?f%5Blanguage_ssim%5D%5B%5D=Italiano&q=): `http://vatican-dev.sul.stanford.edu/overview/catalog?f%5Blanguage_ssim%5D%5B%5D=Italiano&q=`
![language_ssim](https://user-images.githubusercontent.com/5402927/44124246-130bb304-9fe1-11e8-91ff-d2d0c5bf5953.png)

We normalize the language field that's used for facets (`language_ssim`),  but we do not normalize the same data when used on the manuscript show page (`ms_language_ssim`). This should be a part of the team meeting tomorrow.

**Comment by ggeisler** [comment]
Okay thanks @camillevilla. The `Dated_Mss` field issue is fine then. We can just make sure to explain the details of the Curation > Metadata config to the Vatican curators (though it is awkward it's not obvious which applies to which section, but since this is a one-off I think it's fine to live with).

👍 to discussing the language field issue tomorrow. I get why it's different, but we should discuss whether it is technically feasible to normalize both instances in the same way and provide a better user experience.

**Comment by mejackreed** [comment]
Closing based off of discussion on 8/15. BAV team will update their MD to hopefully improve overall user experience.
