### ISSUE TITLE
Manuscript metadata field appears in wrong section; also duplicated

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#269]
I think this might have been correct at some point, but looking at the current deployed app it seems like the `Date` metadata element is in the Description section when it should be in the Manuscript Information section (this is not controllable by the curator on the Configuration > Metadata page, correct?).

Below are my mockup and a current example page. Note that `Beginning date` and `Ending date` appear in both sections, when they should be only in the Manuscript Information section.

![](https://user-images.githubusercontent.com/101482/41804137-407b5a66-7646-11e8-8d6e-86cee9e31adc.png)

---
http://vatican-dev.sul.stanford.edu/overview/catalog/Barb_gr_221

<img width="322" alt="barb_gr_221_-_project_overview_-_thematic_pathways_of_medieval_manuscripts-2" src="https://user-images.githubusercontent.com/101482/42912334-b6e034f8-8aa3-11e8-8044-56028cf53ba4.png">

**Comment by camillevilla** [comment]
Looks like I'm getting slightly different behavior locally:
<img width="637" alt="manuscript_info_date" src="https://user-images.githubusercontent.com/5402927/44062630-044e2326-9f12-11e8-9c47-23418201a55d.png">

**Comment by camillevilla** [comment]
More notes from our traject config:
https://github.com/sul-dlss/vatican_exhibits/blob/5adc64aea08cde9d998cdffb6e62333c00ec3f31/lib/traject/vatican_iiif_config.rb#L279

https://github.com/sul-dlss/vatican_exhibits/blob/5adc64aea08cde9d998cdffb6e62333c00ec3f31/lib/traject/vatican_iiif_config.rb#L29-L38

https://github.com/sul-dlss/vatican_exhibits/blob/5adc64aea08cde9d998cdffb6e62333c00ec3f31/lib/traject/vatican_iiif_config.rb#L133-L137

https://github.com/sul-dlss/vatican_exhibits/blob/5adc64aea08cde9d998cdffb6e62333c00ec3f31/lib/traject/vatican_iiif_config.rb#L213-L216

**Comment by camillevilla** [comment]
@ggeisler I've revisited the dev instance my local copy and it looks like these fields are toggle-able in Curation > Metadata. There *are* three date fields. Is it acceptable to have the Vatican curators toggle these on their own?

**Comment by ggeisler** [comment]
@camillevilla Sure, I think we can set up the Curation > Metadata page to get the intended display and make sure the Vatican curators know how the page works so they understand the ramifications of changes things there.

But I still see the problem the caused me to create this ticket. I've used Curation > Metadata to turn on the three date fields and there are two things that don't seem right:

1. The main date field is not showing up in the Manuscript Info section, even though it appears in the Description section. It should show up in the Manuscript Info section like the other two date fields.

2. When I turn on the date fields they show up in both the Manuscript Info section and in the Description section. The date fields should only be displayed in the Manuscript Info section.

<img width="331" alt="barb_gr_221_-_project_overview_-_thematic_pathways_of_medieval_manuscripts" src="https://user-images.githubusercontent.com/101482/44065237-646708ac-9f1e-11e8-95d9-1bf88c4a5b37.png">

**Comment by camillevilla** [comment]
@ggeisler 😥 It looks like this is another one I was able to resolve with reindexing. I'm going through a reindex of each of the pathways now.
