### ISSUE TITLE
Move item tags to display in Manuscript section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#288]
The manuscript item tags currently display in the Description section, no matter how much priority I give them in the Configuration > Metadata page. I'd like to make them display at the bottom of the Manuscript Information section, so that they are visible without having to expand the More details button.

<img width="658" alt="vat_lat_3195_-_project_overview_-_thematic_pathways_of_medieval_manuscripts" src="https://user-images.githubusercontent.com/101482/44598751-e4c05180-a788-11e8-9462-e5b9bc0d9a64.png">

**Comment by ggeisler** [comment]
@jkeck But it isn’t controllable in the admin interface, in terms of how BAV wants to place it. I understand how the Metadata configuration ordering works in normal exhibits, of course. The difference here is that the Vatican exhibits distribute the metadata fields into two sections on the manuscript show page. Even if I put the Exhibit Tags field directly after the Extent field as in the example exhibit below, the Exhibit Tags field shows up as the first field in the Description section, not the last field in the Manuscript Information section, which is what we want.

See here for the configuration: http://vatican-dev.sul.stanford.edu/overview/metadata_configuration/edit <http://vatican-dev.sul.stanford.edu/overview/metadata_configuration/edit>

And here for an example that shows where the Exhibit Tag field ends up: http://vatican-dev.sul.stanford.edu/overview/catalog/Vat_lat_3195 <http://vatican-dev.sul.stanford.edu/overview/catalog/Vat_lat_3195>

The key thing is the section where the field ends up. We want the Exhibit Tags field to be in the Manuscript Information section, not the Description section, where it currently ends up, even after reordering via configuration. So yes, the configuration ordering works to some extent, it just doesn’t let the Exhibit Tags field move into the earlier section.

**Comment by jkeck** [comment]
Yeah, sorry, I deleted my earlier comment.  I was confused about what the acceptance criteria was for this ticket.  (I saw a big red box around tags at the end of the Description section and said, sure I can do that).  After reading more closely, I believe I understand what you're asking for (and hopefully 🤞 you can validate that based on the screenshot in #351)
