### ISSUE TITLE
Discover and document Vatican data sources used for project

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#3]
Known data sources include:
 - manuscript resources published as IIIF manifests https://digi.vatlib.it/iiif/MSS_Barb.gr.252/manifest.json
 - TEI as metadata enhancement for manifests (title, date, repository, work level titles, incipit)
 - annotation lists for manuscripts (currently hosted in a Colligo instance using annotot)

**Comment by blalbrit** [comment]
[InForMAXMellon.zip](https://github.com/sul-dlss/vatican_exhibits/files/1972407/InForMAXMellon.zip)

**Comment by blalbrit** [comment]
[request.pdf](https://github.com/sul-dlss/vatican_exhibits/files/1972434/request.pdf)

**Comment by mejackreed** [comment]
They can be accessed like so:

https://sul-dms-discovery-stage.stanford.edu/annotations?uri=https%3A%2F%2Fdigi.vatlib.it%2Fiiif%2FMSS_Vat.lat.3225%2Fcanvas%2Fp0005&format=json

Or as an annotationList: https://sul-dms-discovery-stage.stanford.edu/annotations/lists?uri=https%3A%2F%2Fdigi.vatlib.it%2Fiiif%2FMSS_Vat.lat.3225%2Fcanvas%2Fp0005&format=json

**Comment by mejackreed** [comment]
Likely we will need to accommodate future linking of the annotationLists in the manifests.

**Comment by mejackreed** [comment]
I think we can close this issue, I'm not sure there is any actionable work left.
