### ISSUE TITLE
Ensure that date fields only display in main manuscript metadata section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#309]
BAV noted that there are some manuscripts where the date fields are repeated in both the main metadata section and the more details section. They used http://spotlight.bav.local/humanist-library/catalog/Urb_lat_350 as an example of where this happens.

On our dev server, this also occurs in the humanist-library exhibit (http://vatican-dev.sul.stanford.edu/humanist-library/catalog/Urb_lat_350) but not with the same manuscript in the Overview exhibit (http://vatican-dev.sul.stanford.edu/overview/catalog/Urb_lat_350).

It also occurs in other manuscripts on our server (http://vatican-dev.sul.stanford.edu/latin-paleography/catalog/Chig_L_VIII_296 -- but only one of the date fields is repeated) but not others (http://vatican-dev.sul.stanford.edu/overview/catalog/Urb_lat_410). 

So I wonder if this is just an indexing issue, where not all the exhibits are completely up to date?

In any case, we should only display the date fields in the main metadata section, not in the More details section.

**Comment by camillevilla** [comment]
So I have a vague memory of investigating this issue during the work cycle for #269. 

In the case of our dev server, the varying behavior for repeating dates is the `Curation > Metadata` settings. The additional date fields are turned off in the Project Overview exhibit, but not in Latin Paleography. 

We do definitely need both sets of date fields, unfortunately. It's definitely confusing to see multiple date fields in the metadata panel, but they should be able to tell which ones to turn off by looking at the other views selected. 

![vatican_date_fields](https://user-images.githubusercontent.com/5402927/49188011-23345200-f31e-11e8-9f92-e4a2b6347398.png)

**Comment by ggeisler** [comment]
@camillevilla Yes, you're correct. I verified in the BAV exhibit referenced in my my original comment that if I turn off the correct set of date fields we can get things to display in the section we want and not the other. I should've figured this out but because I knew there was some dev work needed to put fields in a specific section I just assumed that was the issue here.

So I'm going to close this ticket because there's no development work needed. I'll just have to work with the BAV curators (or probably just do it for them, which will be easier than trying to explain it) to make sure appropriate set of date fields are checked or unchecked. Thanks!

**Comment by ggeisler** [comment]
Leaving this ticket closed but I've configured all the BAV exhibits on their server and have run into anomalies related to the dates for two exhibits and want to note them here for easy reference later if necessary.

I can't get the `Date` and `Dated Mss` fields to display in the Manuscript Info section no matter what I do with date field configuration in the Overview and Humanist Prince's exhibits. For example, these manuscripts show the `Date` and `Dated Mss` fields in their search result item but won't display them in the Manuscript Info section (though I can set the configuration to display them in the Description section):

http://spotlight.bav.local/overview/catalog/Urb_gr_2
http://spotlight.bav.local/humanist-library/catalog/Urb_lat_281

Other BAV exhibits seem to be configurable the way we want, and also our local dev server exhibits. So for now I'm going to assume it is just a caching issue, or code that isn't updated on BAV servers, and that the problem will go away when the move everything to their production server and all is updated. (Not sure that is a logical assumption, but I don't think it hurts to wait until they migrate to the production server before looking at this more closely, if the problem persists there.)
