### ISSUE TITLE
Add additional sanitized tags for curratorial narrative field

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#317]
add
 - [x] `<i>`
 - [x] `<b>`
 - [x] `<br>`
 - [x] `target`

https://github.com/sul-dlss/vatican_exhibits/blob/master/app/helpers/spotlight_helper.rb#L9

**Comment by ggeisler** [comment]
When this ticket is completed, we should send Paola information about the syntax her curators can use for this tags, especially how to use the target attribute.
