### ISSUE TITLE
Error when changing published status of About pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#320]
In one of the BAV exhibits ([Vatican Palimpsests](http://spotlight.bav.local/palimpsests/about)) the curator is using a strategy that involves creating a large number of About pages (which are not typical about pages but rather a page for each palimpsest). It looks like about 52 of them are published and displaying, but at this point we don't seem to be able to change the status of the remaining 14 or so of them from published to unpublished.

I can successfully create a new about page (see `testpage` at the end of the list), but when trying to change its status to published, the status doesn't stick. Similarly, if I change the status of a currently published about page to unpublished, it also doesn't stick. There is flash error message displayed, so I assume there might be something we can find from from an error log? 

<img width="1201" alt="curation_-_about_pages___vatican_palimpsests_-_blacklight" src="https://user-images.githubusercontent.com/101482/48366658-c5401300-e66b-11e8-9586-df4c65c1c4e6.png">

**Comment by jkeck** [comment]
It looks like our weight has a validation about being w/i a particular range (50 in our case): 
https://github.com/projectblacklight/spotlight/blob/a0c4df0263983c5cf51339d7754ab52f3727f447/app/models/spotlight/page.rb#L22

The MAX_PAGES is a constant that is set to 50.

**Comment by ggeisler** [comment]
That definitely seems to be the cause of the issue then.

Can we up the MAX_PAGES value? Or is that out of our control?

If we can change it, I think only the one exhibit is going to have more than 50 pages, and I believe 70 as a max would be sufficient for him.
