### ISSUE TITLE
Do curatorial narratives need to be duplicated for Overview exhibit?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#326]
I think the answer is yes but want to be sure before giving BAV a definitive answer. They want to know whether -- in order for the curatorial narrative associated with a given manuscript to be visible in both its topic-specific exhibit and the overview exhibit -- they will need to create separate, duplicated curatorial narrative texts, one for the item in the topic exhibit and again for the item in the overview exhibit.

**Comment by cbeer** [comment]
Yes, they need to be duplicated. Narratives are exhibit-specific content and there's no mechanism for sharing them across exhibits.
