### ISSUE TITLE
Install annotot and import vatican data sample

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#34]
This assumes vatican_exhibits as a replacement for colligo.

Some annotot data stored on [dms-discovery-stage](https://sul-dms-discovery-stage.stanford.edu/?f%5Bcollection%5D%5B%5D=Test+collection). But we likely need to create/document an export / import strategy.

Look into restricting access to write/delete routes for annotot

github.com/mejackreed/annotot

See diagram in #21

**Comment by mejackreed** [comment]
We will need to pair with @blalbrit or @eefahy here to get data from BAV server to do something like:

```sh
$ mysqldump -u $RDS_USERNAME -p $RDS_PASSWORD $RDS_DB_NAME  annotot_annotations > annotot_annotations.sql 
```

I'm assuming these ENV vars are available looking at https://github.com/sul-dlss/colligo/blob/vatican/config/database.yml

Or another option is to add something like this to colligo: https://github.com/rroblak/seed_dump

But that would require us to do deploy a new version of the software.. I'm not sure how feasible that is .

**Comment by mejackreed** [comment]
Pairing w/ @blalbrit today we downloaded some logs .. a few gists here of failed updates:

https://gist.github.com/blalbrit/65746f0e4bbda8b16b9186e5974b6296
https://gist.github.com/blalbrit/897dfb69484a83034667889f45c6a6f0

And a successful one:
https://gist.github.com/blalbrit/490fe02f19e4370004ca329e0a11a607

**Comment by mejackreed** [comment]
I have a sql file from their prod database now and have imported successfully locally. How should we proceed with this further?

**Comment by mejackreed** [comment]
Before importing on our server, lets get some type of auth up: https://github.com/sul-dlss/vatican_exhibits/pull/81

**Comment by mejackreed** [comment]
I was able to import locally doing the following: `bundle exec rails db < $SQL_FILE`

**Comment by cbeer** [comment]
I've imported the annotations to the -dev site.
