### ISSUE TITLE
Can translations of field labels be copied between exhibits via the database?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#355]
I know in general we wouldn't want to mess with the database directly to do something like this, but if this is possible it would save BAV a lot of tedious manual data entry so want to check before instructing BAV on how to proceed.

There are six BAV exhibits and each of them will use the same Italian translation values for all of the metadata field labels and the search field labels (including the facet labels). As you know, the BAV exhibits have lots of metadata fields. Paola intends to have a single list of translations for all of these fields.

So the question is: can we (A) enter the translations once in one exhibit and then do some manual database copy and paste (within the Translations table) to directly add the same translations for the other five exhibits or do we need to (B) manually enter all the translations for all six exhibits via the Curation > Translations UI?

Looking at the Translations table in the db it feels like it might be technically possible, but am not sure if there are potential complications that I'm not aware of that would make the (A) approach above inadvisable.

**Comment by cbeer** [comment]
Then, yeah, we can probably figure that out. I assume someone has access to their new environment.

**Comment by ggeisler** [comment]
Okay, great. I don't think the work needs to/will be ready to happen anytime real soon. But this answer enables me to tell the curators that they should coordinate internally and only manually enter the translations for the the fields in one exhibit when they get do started, rather than independently adding them in their own exhibits. 

I'll create a new ticket for the db work when they actually have the translations ready to duplicate in the other exhibits.
