### ISSUE TITLE
Remove cloned feature pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#386]
The Latin Classics exhibit on the BAV local server has two sets of duplicate feature pages:

<img width="727" alt="duplicate-feature-pages" src="https://user-images.githubusercontent.com/101482/55662553-18586500-57c9-11e9-96a1-7c51b4b66639.png">

These seem to be synchronized clones, in that they have the exact same URL and when I edit one, the change shows up in the other.

These pages **have a lot** of content, so I'm hesitant to try to figure out way to fix this via the UI (e.g., it seems likely that if I try to delete one clone, it will delete them both). 

Hopefully there is a straightforward way to delete one copy of each cloned pair directly in the database. The pages are:

http://spotlight.bav.local/latin-classics/feature/livius-titus-59-a-c-17-d-c
http://spotlight.bav.local/latin-classics/feature/seneca-lucius-annaeus-5-4-a-c-65-d-c

**Comment by mejackreed** [comment]
We haven't been able to find instances of this available in prod anymore.

**Comment by mejackreed** [comment]
Closing as we can't find instances of this anymore.
