### ISSUE TITLE
Can't publish/unpublish pages in Palimpsests exhibit

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/vatican_exhibits#390]
BAV reported that they are unable to publish or unpublish feature pages in the Palimpsests exhibit:

http://spotlight.bav.local/palimpsests/feature

I've confirmed that trying to publish or unpublish a page from the Curation > Feature pages list results in an exception with this URL: http://spotlight.bav.local/palimpsests/feature/update_all

I can, however, successfully publish or unpublish a page from the Options tab when editing the page directly, so this seems specific to the Curation > Feature pages context.

BAV reported the same problem with the Latin Classics exhibit, but I can't recreate the problem there. I am able to publish and unpublish in that exhibit from the Curation > Feature pages context.

**Comment by mejackreed** [comment]
Resolved locally in #395 and fixed upstream in https://github.com/projectblacklight/spotlight/pull/2162
