### ISSUE TITLE
Sometimes redirect to Home

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#411]
Report:
```
[note - this is different behavior… just one particular page within Latin Classics exhibit]
```

Sometimes something in Latin Classics gets redirected to home page? Need more analysis / HB

**Comment by mejackreed** [comment]
@blalbrit I can't seem to find the error here or able to recreate it. Do you have more context you can provide?

**Comment by blalbrit** [comment]
@mejackreed - I have pinged Paola in the doc to see if she can point us directly to the issue. In the meantime, here's her thread on the Latin Classics issues:

```

Dear Jack,

Hope this finds you well.

We have some remaining issues in the Latin Classics exhibit:

- feature page: "AND THE OTHERS". 
https://spotlight.vatlib.it/latin-classics/feature/and-the-others

This page has been filled using the widget "saved searches"
If you try to edit it, widgets bar is unavailable.

- in these pages we cannot edit the contents previously filled.: 
https://spotlight.vatlib.it/latin-classics/feature/cicero-marcus-tullius-106-43-a-c/edit
https://spotlight.vatlib.it/latin-classics/feature/horatius-flaccus-quintus-65-a-c-8-d-c/edit
https://spotlight.vatlib.it/latin-classics/feature/terentius-afer-publius-c-195-159-a-c/edit
https://spotlight.vatlib.it/latin-classics/home/edit

It seems to us that the use of  the widget "Items slide show" (all of them have at least one "Item slide show" embedded in each page) is blocking the display of the content below this component.

- In this specific pages we cannot edit  and save the right URLs

https://spotlight.vatlib.it/latin-classics/feature/vergilius-maro-publius-70-19-a-c
https://spotlight.vatlib.it/latin-classics/feature/federico-veterani-m-dopo-il-1526

For all of these issues: we have already tried to restart the SOLR... but nothing changed.
```

**Comment by blalbrit** [comment]
I take that back - Paola has provided documentation for this in the Google doc already:

```
[BLOCKER]:

This page:

https://spotlight.vatlib.it/en/latin-classics/feature/maestro-del-messale-orsini

apparently links the  home page (seeing classics)
If you change language you will get en error
 "The page you were looking for doesn't exist."

while the correct ENG page for maestro del messale orsini is

https://spotlight.vatlib.it/en/latin-classics/feature/maestro-del-messale-orsini-sec-xv-med-cef46e8d-7892-466f-80dd-c1775cd6755e

From here if you change language (to ITA) you get the Italian correct page

https://spotlight.vatlib.it/it/latin-classics/feature/maestro-del-messale-orsini-sec-xv-med

BUT if you go back again to the ENG version you will get this:
https://spotlight.vatlib.it/en/latin-classics/feature/maestro-del-messale-orsini-sec-xv-med
(the false "Seeing classics" home page)

This issue is documented in the video recording prepared by Domenico (cfr. his email, last May 23 "CASE 4 - Multilink, crossed link and language change")

```

**Comment by blalbrit** [comment]
I get the error immediately when following the instructions above.

**Comment by mejackreed** [comment]
Gotcha, thanks. So I'm thinking then the Italian version of the page may be linked to the wrong parent?

Maybe a good pairing oppy to see if this is more of a data remediation task or something for us to look at fixing in the code.

**Comment by mejackreed** [comment]
Ok we have fixed the underlying issue here with data remediation for the page `https://spotlight.vatlib.it/en/latin-classics/feature/maestro-del-messale-orsini-sec-xv-med-cef46e8d-7892-466f-80dd-c1775cd6755e`

However, this bug still exists in Spotlight. So if I page that has a UUID slug at the end of it (due to an original page being deleted and recreated with the same name), when a translated page is created, it will present this bug.

This is related to how FriendlyId removes the UUID from a slug when you `#dup` it. 

Related: https://github.com/norman/friendly_id/blob/9cd4ce2b5d0425aa704872e1334b442cab03c29c/lib/friendly_id/base.rb#L271

And happening in Spotlight:
https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/page.rb#L133-L145
