### ISSUE TITLE
Investigate image upload failure

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#415]
Reported by Anna on June 4. Investigate HB?

```
I point you that the function "upload an image" in "Edit Browse Category" > "Thumbnail" doesn't work.
I tried to upload some images from my desktop but they don't appear.
And sometimes it's also happened in "From this exhibit" where there aren't all exhibited items (Domenico Surace -for Path C- told me about some manuscripts like e.g. Vat.gr.154 or Vat.gr.21).
Thanks in advance,
```

**Comment by mejackreed** [comment]
I'm thinking perhaps this could be due to session caching and CSRF? Maybe the course of action is to log out and log back in?

**Comment by jkeck** [comment]
@mejackreed do you know if this is reproducible locally or is this only happening in the production context?

**Comment by jkeck** [comment]
Okay, I was able to reproduce this locally

**Comment by jkeck** [comment]
If I run this on a spotlight that has `remote: false` in the `bootstrap_form_for` tag then this seems to work in Vatican Exhibits (not sure why this is though, and why this doesn't affect our spotlight instance)

**Comment by jkeck** [comment]
This appear to be an issue w/ turbolinks.  I can only reproduce when trying to upload when navigating from another page (doing the upload from a refresh does not return the `InvalidAuthenticityToken` error).  This is all sounding familiar, but not remembering what we did/how we've dealt w/ this before.

**Comment by mejackreed** [comment]
Ah.. so maybe do this https://github.com/projectblacklight/spotlight/pull/2121/files on this: https://github.com/projectblacklight/spotlight/blob/master/app/views/spotlight/shared/_configuration_sidebar.html.erb ???

**Comment by jkeck** [comment]
That seems a bit heavy handed, but may be a good last-ditch effort.  I'm still trying to determine why this happens in this app and not our own.

**Comment by mejackreed** [comment]
Fixes in https://github.com/projectblacklight/spotlight/pull/2176
