### ISSUE TITLE
As a Vatican exhibit admin, I want to be able to index (and reindex) the objects in my exhibit - including descriptive metadata and annotations - at will

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#5]
- During development phase - reindexing annotations regularly into Spotlight 
 - During production phase - possibility of curation team reindexing periodically
 - Re-indexing should be an activity run by a curator through a button in the curator dashboard - reindexing of objects, object metadata, and annotations (including tags - iiif annotationlist tags)
 - Annotation Tags should be a facet in the search & browse UI of the “Spotlight” exhibits

**Comment by cbeer** [comment]
I think with #173 we can call this done?

**Comment by mejackreed** [comment]
Yep.
