### ISSUE TITLE
Improve UI for adding a manifest + TEI 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/vatican_exhibits#60]
Ideas from @cbeer:
- Provide a list of shelfmarks
- set manifest and TEI URLs elsewhere in the interface

Current interface:
<img width="897" alt="screen shot 2018-05-24 at 10 12 56 am" src="https://user-images.githubusercontent.com/5402927/40500877-0ed08eae-5f3b-11e8-9ac9-a9f5c73e3e1f.png">

**Comment by blalbrit** [comment]
@mejackreed - you got it right. The primary manifests are listed in the .html files at https://github.com/sul-dlss/bav_stanford . There might be some changes, but that's pretty much the scope. In this case, each pathway corresponds to an exhibit *except* pathway-a, which will be split into two exhibits.

**Comment by mejackreed** [comment]
So with that.. perhaps exhibits could be "preseeded" with seed data?

**Comment by blalbrit** [comment]
Absolutely!

**Comment by mejackreed** [comment]
Perhaps we could use the JSON file from @jkeck to automate using db:seed 5 exhibits + all shelfmarks

**Comment by jkeck** [comment]
It looks like #72 does that. Do we need to do something w/ the UI?  Do we still want to allow people to attempt to add documents that we don't already know about?

I would be happy to take a crack and just displaying the "shelfmarks" or whatever we want to display to users in this UI, but not sure if this should go in Design Needed or not.

**Comment by mejackreed** [comment]
I wonder if we can get a reaction first from the Vatican team to understand a bit better how they want to use this. Perhaps #72 is good enough for now and close this to come back to it when we have more to go off of?

**Comment by mejackreed** [comment]
Closing this for now, until we get some feedback or want to reopen and prioritize.
