### ISSUE TITLE
Validate manifests in Mirador Widget

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/vatican_exhibits#85]
Larger design ticket: sul-dlss/exhibits#1002

![screenshot](https://user-images.githubusercontent.com/101482/38783255-a193d7e6-40b4-11e8-8437-8e87dfccaaf6.png)

### Notes
We want to distinguish between the following types of errors:
- URL not found
- malformed manifest

**Comment by camillevilla** [comment]
Closed by #99
