### ISSUE TITLE
Add "Preview and configure viewer" button/popup to mirador widget

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/vatican_exhibits#88]
Larger design ticket: sul-dlss/exhibits#1002

The popup should persist the Mirador state in the field provided by #69 

![widget-ui](https://user-images.githubusercontent.com/101482/38783405-8271baac-40b6-11e8-8f9d-f2028877fbd5.png)

![popup-ui](https://user-images.githubusercontent.com/101482/40752248-978eb008-6423-11e8-92e6-b0e70961d2f0.png)

**Comment by mejackreed** [comment]
Resolved in #160
