### ISSUE TITLE
Design for vatican metadata search and display

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#9]
We need some designs to drive metadata search and display

**Comment by mejackreed** [comment]
What is the superset that we want to display and search on

**Comment by caaster** [comment]
- Is the TEI data that we have now representative of the final state? 
- Has the TEI schema been finalized or will that work continue through 2020?
- Do we know, if the schema isn't final yet, will it change significantly or not?
- Are Vatican folks expecting to see _all_ fields represented in this screenshot on the show page?
https://drive.google.com/file/d/1m_EAA802LvwXHmXaa0Lc_PeuUyUBpcLW/view
- Do we know if any of these are composed fields?
