### ISSUE TITLE
Get vatican off of colligo

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#94]
- [x] Resolve #95 
 - [ ] confirm they can deploy vatican exhibits
 - [x] upload latest annotations from colligo
 - [x] switch over mirador instances to use new vatican exhibits url 
 - [x] configure api get thingy for mirador
 - [x] Run annotation remediation task https://github.com/sul-dlss/vatican_exhibits/pull/135

Need to consider timing here (anytime in afternoon PT)

**Comment by cbeer** [comment]
Blocked waiting for the spotlight.bav.local server.

**Comment by cbeer** [comment]
Blocked waiting for confirmation that BAV can updating and redeploy the app
