### ISSUE TITLE
Troubleshoot vatican deployed application

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#95]
Passenger seems to have difficulty running and errors are in error log `/var/log/httpd/error_log`

**Comment by mejackreed** [comment]
It appears that https://github.com/sul-dlss/vatican_exhibits/blob/master/system-setup/100-install_app_dependencies.sh was run as root.

**Comment by mejackreed** [comment]
Riccardo is going to provide videos of the issues he is having

**Comment by caaster** [comment]
We now have videos & have watched them, and we have sent Riccardo more questions.

**Comment by cbeer** [comment]
Done?
